apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: kubeflow aws setup
  version: 0.1.26
spec:
  dependencies:
  - name: aws-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - aws
